---
title: "Uitgaven veiligheid"
author: "Junior Burssens"
date: "20-03-2015"
output: word_document
csl: apa.csl
bibliography: Economics of Security.bib
---
# Selectie teksten

Volgens Becker [@becker_crime_1968] zou een verschil in uitgaven voor criminaliteitsbeheersing moeten leiden tot een verschil in criminaliteitsniveau. Extra politie verhoogt immers de pakkans bij eenzelfde bestraffingsniveau. Anderzijds illustreert Van Reenen [@vanreenen_unpayable_1999] de toepasbaarheid van Baumol's *cost disease* op politie: uitgaven zijn vooral gebonden aan personeelskosten en kunnen blijven stijgen zonder een daadwerkelijk verschil te maken in het beoogde resultaat. Daarbovenop is er een normatief effect aan het werk en speelt het monopolie van de politie een belangrijke rol.

Worral [@worrall_effects_2008] onderzocht het effect dat LLEBG (Local Law Enforcement Block Grants) subsidies in de VS hadden op de reductie van ernstige criminaliteit en stelde vast dat de extra financiering leidde tot een significante reductie. De daling werd echter niet veroorzaakt door de extra politiecapaciteit, maar door een ander, niet geïdentificeerd, mechanisme.

In de VS werd het effect van de uitgaven voor politie op criminaliteit onderzocht door Levitt [@levitt_using_1997]. Hij gebruikt het feit dat de uitgaven voor politie stijgen in een lokaal verkiezingsjaar als instrumentvariabele voor de werkelijke uitbreiding van de politie. Hij lost hiermee het endogeniteitsprobleem op, waarbij het criminaliteitsniveau en de politiecapaciteit gezamenlijk bepaald worden door bijvoorbeeld een grootstedelijke context. Hij bevestigt de hypothese dat een stijging in de politiecapaciteit criminaliteit reduceert, zij het in verschillende mate naargelang het type criminaliteit.

Vanuit bestuurlijk oogpunt is het optimale niveau van uitgaven voor politie moeilijk te bepalen. Correa [@correa_optimal_2005] tracht dit op te vangen door het begrip schade te gebruiken. Schade omvat daarbij de totale kost veroorzaakt door criminaliteit en politiebescherming. Wanneer men deze kost weet te minimaliseren, zal het optimum bereikt worden.

Imrohoroğlu et al. [@imrohoroglu_political_2000] onderzoeken het verband tussen lokale uitgaven aan politie, herverdeling en criminaliteit. Zij trachten via een *general equilibrium model* na te gaan of een beleid van extra investeringen in politie, dan wel een focus op herverdeling van inkomen criminaliteit reduceert. Het model toont aan dat een verhoging van de uitgaven voor politie de criminaliteit vermindert, maar met afnemende meeroprbrengsten. Herverdeling van het inkomen leidde evenwel tot een stijging van de criminaliteit, omdat het aantal inactieven toeneemt en het inkomen uit legale activiteiten relatief lager is.

Uit onderzoek naar doelwitselectie van inbrekers [@vandeviver_rol_2012;@vandeviver_what_2015 ] blijkt dat de fysieke toegankelijkheid van de inbraakbuurt hierin een belangrijke factor vormt. Concreet kennen buurten langs belangrijke verkeeraders en doorgangsroutes en met een hogere dichtheid aan wegen, ceteris paribus, een hogere kans op inbraken.

VERDER LEZEN [@kelejian_suggested_1993] spatiaal model van lokale uitgaven (County)
VERDER LEZEN, ARTIKEL NIET BENADERBAAR HOEWEL IN UGENT CATALOOG [@schwab_disentangling_1987] schat kost- en productiefuncties voor uitgaven aan politie. Waarschuwt voor het ontbreken van bevolkingsvariabelen in schattingen, wegens mogelijk sterk vertekende resultaten.

# Inleiding en probleemstelling

Met de politiehervorming wijzigde ook de financiering van de lokale politie voor de gemeenten. Vanaf 2002 ging een systeem van overdrachten naar de zone in voege, vergelijkbaar met de financiering van bijvoorbeeld de OCMW's.^[Misschien wat concreter uitdiepen voor de leek?] Opvallend is dat de gemiddelde dotatie aan de zones ieder jaar steeg, maar dat die trend in 2013 werd onderbroken. Men zou dit gemakshalve kunnen wijten aan de crisis of aan de besparingszucht van ijverige politici, maar we hopen met deze bijdrage de oorzaken van deze daling te achterhalen en de uitgaven aan de lokale politie door de gemeenten in kaart te brengen. Meerbepaald proberen we te achterhalen of het budgettair beleid zich afstemt op de veiligheidsnoden van de gemeente. Men mag immers verwachten dat een stijging van de criminaliteitscijfers voor de beleidsmakkers een trigger kan vormen om meer te investeren in haar politie. Dit zou gereflecteerd moeten worden in de uitgaven voor politie, maar ook in het aandeel dat de politie-uitgaven krijgen in de totale uitgaven van de gemeente.

Paragraaf maatschappelijke relevantie: parlementaire vragen, politievakbond, meergemeentezones, korpschef.

Paragraaf context gemeente-uitgaven.

# Literatuur

Paragraaf wat bepaalt uitgaven voor politie?veiligheid?
Paragraaf hoe verhouden politie-uitgaven zich tot de andere uitgaven?s
Deller et al. [@deller_model_2006] vinden bewijs voor verschillen in de onderlinge verhoudingen van uitgaven wanneer het totale budget daalt of stijgt, ten gevolge van een wijziging van de federale subsidies. Bij een daling wordt er minder snel bespaard op politie of brandweer.


# Bibliografie